#!/usr/bin/env python3
"""Build data.js for the interactive ratchet figures.

Reads the per-path `summary_N_*_psi_*.csv` files, groups by (psi, delta) and
stores per-group mean/std of t_0 and 1/t_0 (computed over finite, strictly
positive t_0 only). All y-axis quantities the page offers are scalar multiples
of mean(t_0) or mean(1/t_0), so storing these four numbers is enough to render
every "transform-then-average" curve exactly.

Run again whenever the CSVs change:  python3 build_data.py
"""
import csv
import glob
import json
import math
import os
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "ratchet_discrete_psi_delta_stop_at_t0_results")
OUT = os.path.join(HERE, "data.js")


def fnum(s):
    """Parse a CSV cell to a finite float, else None (empty / inf / NaN)."""
    s = (s or "").strip()
    if not s:
        return None
    try:
        v = float(s)
    except ValueError:
        return None
    return v if math.isfinite(v) else None


groups = {}
for path in sorted(glob.glob(os.path.join(DATA_DIR, "summary_N_*_psi_*.csv"))):
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            key = (float(row["psi"]), float(row["delta"]))
            g = groups.get(key)
            if g is None:
                g = groups[key] = {
                    "psi": float(row["psi"]),
                    "delta": float(row["delta"]),
                    "N": int(float(row["N"])),
                    "alpha": float(row["alpha"]),
                    "lambda": float(row["lambda"]),
                    "theta": float(row["theta"]),
                    "effective_beta": float(row["effective_beta"]),
                    "n_total": 0,
                    "n_hit": 0,
                    "t0": [],
                }
            g["n_total"] += 1
            if row["hit_x0_zero"].strip() == "True":
                g["n_hit"] += 1
            t0 = fnum(row.get("t_0"))
            if t0 is not None and t0 > 0:
                g["t0"].append(t0)

points = []
for key in sorted(groups):
    g = groups[key]
    t0 = g["t0"]
    n_used = len(t0)
    if n_used >= 1:
        inv = [1.0 / x for x in t0]
        mean_t0 = statistics.fmean(t0)
        mean_inv = statistics.fmean(inv)
        std_t0 = statistics.stdev(t0) if n_used >= 2 else 0.0
        std_inv = statistics.stdev(inv) if n_used >= 2 else 0.0
    else:
        mean_t0 = std_t0 = mean_inv = std_inv = None
    points.append({
        "psi": g["psi"],
        "delta": g["delta"],
        "N": g["N"],
        "alpha": g["alpha"],
        "lambda": g["lambda"],
        "theta": g["theta"],
        "effective_beta": g["effective_beta"],
        "n_total": g["n_total"],
        "n_hit": g["n_hit"],
        "frac_hit": g["n_hit"] / g["n_total"] if g["n_total"] else 0.0,
        "n_used": n_used,
        "mean_t0": mean_t0,
        "std_t0": std_t0,
        "mean_inv_t0": mean_inv,
        "std_inv_t0": std_inv,
    })

out = {
    "N_values": sorted({p["N"] for p in points}),
    "psi_values": sorted({p["psi"] for p in points}),
    "points": points,
}
with open(OUT, "w") as fh:
    fh.write("// auto-generated by build_data.py - do not edit by hand\n")
    fh.write("const RATCHET_DATA = ")
    json.dump(out, fh, indent=1, allow_nan=False)
    fh.write(";\n")

print(f"wrote {OUT}: {len(points)} (psi,delta) points; "
      f"psi={out['psi_values']}; N={out['N_values']}")
